# Note: It requires docker-compose 1.13.0
#
# Usage: docker-compose up -d
version: "2.2"

services:
  zalenium:
    image: "dosel/zalenium"
    container_name: selenium-grid_mobile-sample
    hostname: zaleniumhub
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - BROWSER_STACK_USER=javierre3
      - BROWSER_STACK_KEY=bzEKsszL8NzqsNsskaDk
    command: >
      start --desiredContainers 0
            --maxDockerSeleniumContainers 10
            --timeZone "America/Argentina/Buenos_Aires"   
            --browserStackEnabled true
            
            
 # Docker-Android for Android application testing
  #samsung_s7_9.0:
    #image: budtmo/docker-android-x86-9.0
    #privileged: true
    #Increase scale number if needed
    #scale: 1
    #depends_on:
      #- zalenium
    #ports:
      #- 6080:6080
    #Change path of apk that you want to test. I use sample_apk that I provide in folder "example"
    #volumes:
      #- ${apkDirectory}:/root/tmp/sample_apk
      #- ./video-samsung_s7_9:/tmp/video
    #environment:
      #- DEVICE=Samsung Galaxy S7
      #- CONNECT_TO_GRID=true
      #- APPIUM=true
      #- SELENIUM_HOST=zalenium
      #- AUTO_RECORD=false
